# Netlify配置
[build]
  base = "www"
  command = "npm run build"
  publish = "dist"

# 重定向规则 - SPA支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 自定义头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态资源缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"